# 名称
name: Build and Push Java Docker Image

# 触发条件
on:
  push:
    # Push 到 main 分支触发
    branches: [main]
    
# 定义环境变量
env:
  DOCKER_IMAGE_NAME: chatgpt-web-java
  DOCKER_IMAGE_TAG: latest

# 定义构建和推送 Docker 镜像的任务
jobs:
  build:
    # 脚本运行在容器中镜像是 ubuntu-latest
    runs-on: ubuntu-latest

    # 定义任务中的步骤
    steps:
      # 从 Github 仓库中获取代码
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 设置 JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          # openJDK 17
          distribution: 'adopt'
          java-version: '17'
          
      # Maven 缓存
      - name: Maven Dependies Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: chatweb-web-java-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            chatweb-web-java-maven-
            
      # 编译打包      
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      
      # 登录到 Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # 使用 Docker Buildkit 构建和推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_jar
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        env:
          DOCKER_BUILDKIT: 1 # 启用BuildKit构建引擎
